name: scrape-news-hourly
on:
  schedule:
    - cron:  '0 * * * *'        # every hour
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.13'}
      - run: pip install google-genai gspread feedparser python-dotenv
      - run: python news_worker.py
        env:
          GOOGLE_API_KEY:  ${{ secrets.GOOGLE_API_KEY }}
          # no Discord token needed—this job only scrapes
