name: daily-news-and-digest
on:
  schedule:
    - cron:  '0 0 */3 * *'        # every 3 days at midnight UTC
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.13'}
      - run: pip install discord.py gspread google-generativeai feedparser python-dotenv arxiv selenium beautifulsoup4 requests urllib3
      - run: python arxiv_worker.py
        env:
          GOOGLE_API_KEY:  ${{ secrets.GOOGLE_API_KEY }}
          RAW_SHEET_ID: ${{ secrets.RAW_SHEET_ID }}
      - run: python newsapi.ai_worker.py
        env:
          GOOGLE_API_KEY:  ${{ secrets.GOOGLE_API_KEY }}
          RAW_SHEET_ID: ${{ secrets.RAW_SHEET_ID }}
          NEWSAPI_AI_KEY: ${{ secrets.NEWSAPI_AI_KEY }}
      - run: python bot.py
        env:
          GOOGLE_API_KEY:  ${{ secrets.GOOGLE_API_KEY }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          YOUR_CHANNEL_ID: ${{ secrets.YOUR_CHANNEL_ID }}
          RAW_SHEET_ID: ${{ secrets.RAW_SHEET_ID }}
